#Provide the taskId if you are updating the task
task_id: 'Fd8wkfKeNZxyG6S8m2wqbuVQP81M9ywwHNPtj19QRyQA'
# Name and description of your task
task_name: 'hello-world'
task_description: 'This is a simple task that returns "Hello, World!"'

# Network value can be DEVELOPMENT, ARWEAVE or IPFS
task_executable_network: 'IPFS'

# Provide your web3.storage key as it is needed for uploading your metadata
secret_web3_storage_key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGFFQjkyOEFhY2UwNDYwZTg0QzRlYzRDY0Q3ZTcxMjNCMzMyNDNmRDUiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2ODk3MTIyMDA5NjUsIm5hbWUiOiJjb29sVG9rZW4ifQ.HJ3Sac0CeKewlGM26wxRctAcjFPk8RMYpvsjLgHtDrw'

# Path to your executable webpack if the selected network is IPFS otherwise leave blank
task_audit_program: 'dist/main.js'

# Provide your transaction ID in case of ARWEAVE and in case of DEVELOPMENT give your executable name as main otherwise leave blank
task_audit_program_id: 'main'

# Total round time of your task: it must be given in slots and each slot is roughly equal to 4ms
round_time: 1500

audit_window: 300
submission_window: 300

# Amounts in KOII

minimum_stake_amount: 2

# total_bounty_amount cannot be greater than bounty_amount_per_round
# total bounty is not accepted in case of update task
total_bounty_amount: 50

bounty_amount_per_round: 1

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 3

#Space in MBs
space: 1

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer to the type, value, and description format shown below

author: 'Cool Dev'
description: 'This is a simple task that returns "Hello, World!"'
repositoryUrl: 'https://github.com/koii-network/hello-world'
imageUrl: 'Enter you image URL'
requirementsTags:
  - type: CPU
    value: '4-core'
  - type: RAM
    value: '5 GB'
  - type: STORAGE
    value: 'test'
  - type: NETWORK
    value: 'test'
  - type: ARCHITECTURE
    value: 'AMD'
  - type: OS
    value: 'OSX'
