# Name and desciption of your task
task_name: "test-task"
task_description: "This task is to test out the namespace function"
# network value can be DEVELOPMENT , ARWEAVE or IPFS
task_executable_network: "DEVELOPMENT"
# Provide your web3.storage key as it is needed for uploading your metadata
secret_web3_storage_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDg0NmM5YjRmNTMwYzc3OUQ5NzFkOTQzMGI4OTkyRkU5NWIwNTE0MkIiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NjE5ODEwNTg0NjYsIm5hbWUiOiJrb2lpIn0.m0J9abCa_N6M5jJ5quEJkZkbxBP18U-omSQRcXP9a80"

# Path to your executable webpack if the selected network is IPFS otherwise leave blank
task_audit_program: ""

# Provide your transaction ID in case of ARWEAVE and in case of DEVELOPMENT give your executable name as main otherwise leave blank
task_audit_program_id: "main"

# Total round time of your task : it must be given in slots and each slot is rougly equal to 4ms
round_time: 600

audit_window: 200
submission_window: 200

# Amounts in KOII

minimum_stake_amount: 5
total_bounty_amount: 10
bounty_amount_per_round: 1

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 4

#Space in MBs
space: 10

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer the type,value,description format shown below

author: "Your name"
description: "This is test"
repositoryUrl: "github.io/did"
createdAt: 20230324
imageUrl: "cscefve"
requirementsTags:
  - type: GLOBAL_VARIABLE
    value: "TASK_ID"
    description: "used globally 1"
  - type: GLOBAL_VARIABLE
    value: "WEB3.STORAGE"
    description: "used globally 2"
  - type: TASK_VARIABLE
    value: "VAR1"
    description: "used in task 1"
  - type: TASK_VARIABLE
    value: "VAR2"
    description: "used in task 2s"
  - type: CPU
    value: "4-core"
  - type: RAM
    value: "5 GB"
  - type: STORAGE
    value: "test"
  - type: NETWORK
    value: "test"
  - type: ARCHITECTURE
    value: "ccc"
  - type: OS
    value: "OSX"
